package keyboards

// Article
const AddArticle = "✏️ Add article"
const Profile = "👤 Profile"
const Statistics = "📊 Statistics"
const RandomArticle = "🎲 Random article"
const ShowArticles = "📖 Show articles"
const ReadArticle = "📖 Read"
const UnreadArticle = "📖 Unread"
const DeleteArticle = "🗑️ Delete"
const HideRead = "👁️ Hide read"
const ShowRead = "👁️ Show read"
const PrevPage = "⬅️ Previous page"
const NextPage = "➡️ Next page"
const SelectArticle = "🔍"
const SetPublic = "🔈 Make me public"
const HideUser = "🔇 Hide me"
const EditDesc = "💡 Edit desc"
const GetVibe = "🗳️ Get vibe"
